# **Exploring Business Use Cases with SQLite in Python**

###In today's lesson we will be exploring the popular business use case for the **Country Club Database**.


---

**Note:** Ensure the `country_club.db` file is in your working directory before running the notebook. Do so by running the line of code below and finding the database created now in your Colab environment within Files.

In [23]:
# %run cclub_tabs_db_objs.py

# **STEP ONE**

*   Import all necessary libraries and packages.
*   Establish the path to the DB stored in Files.

In [24]:
import sqlite3
import pandas as pd

# Set the path to the SQLite database
db_path = "country_club.db"

# Connect to SQLite database
conn = sqlite3.connect(db_path)

# Confirmation
print("Connected to SQLite  database!")

Connected to SQLite  database!

# **The Bookings Table**

In [25]:
query_bookings = """SELECT *
                    FROM bookings;"""

# Execute the query using pd.read_sql.
df_bookings = pd.read_sql(query_bookings, conn)

display(df_bookings)

      bookid  facid  memid            starttime  slots
0          0      3      1  2012-07-03 11:00:00      2
1          1      4      1  2012-07-03 08:00:00      2
2          2      6      0  2012-07-03 18:00:00      2
3          3      7      1  2012-07-03 19:00:00      2
4          4      8      1  2012-07-03 10:00:00      1
...      ...    ...    ...                  ...    ...
4039    4039      8     29  2012-09-30 18:00:00      1
4040    4040      8     21  2012-09-30 18:30:00      1
4041    4041      8     16  2012-09-30 19:00:00      1
4042    4042      8     29  2012-09-30 19:30:00      1
4043    4043      8      5  2013-01-01 15:30:00      1

[4044 rows x 5 columns]

# **The Members Table**

In [26]:
query_members = """SELECT *
                    FROM members;"""

# Execute the query using pd.read_sql
df_members = pd.read_sql(query_members, conn)

display(df_members)

,memid,surname,firstname,address,zipcode,telephone,recommendedby,joindate
0,0,GUEST,GUEST,GUEST,0,(000) 000-0000,0,2012-07-01 00:00:00
1,1,Smith,Darren,"8 Bloomsbury Close, Boston",4321,555-555-5555,0,2012-07-02 12:02:05
2,2,Smith,Tracy,"8 Bloomsbury Close, New York",4321,555-555-5555,0,2012-07-02 12:08:23
3,3,Rownam,Tim,"23 Highway Way, Boston",23423,(844) 693-0723,0,2012-07-03 09:32:15
4,4,Joplette,Janice,"20 Crossing Road, New York",234,(833) 942-4710,1,2012-07-03 10:25:05
5,5,Butters,Gerald,"1065 Huntingdon Avenue, Boston",56754,(844) 078-4130,1,2012-07-09 10:44:09
6,6,Tracy,Burton,"3 Tunisia Drive, Boston",45678,(822) 354-9973,0,2012-07-15 08:52:55
7,7,Dare,Nancy,"6 Hunting Lodge Way, Boston",10383,(833) 776-4001,4,2012-07-25 08:59:12
8,8,Boothe,Tim,"3 Bloomsbury Close, Reading, 00234",234,(811) 433-2547,3,2012-07-25 16:02:35
9,9,Stibbons,Ponder,"5 Dragons Way, Winchester",87630,(833) 160-3900,6,2012-07-25 17:09:05
10,10,Owen,Charles,"52 Cheshire Grove, Winchester, 28563",28563,(855) 542-5251,1,2012-08-03 19:42:37
11,11,Jones,David,"976 Gnats Close, Reading",33862,(844) 536-8036,4,2012-08-06 16:32:55
12,12,Baker,Anne,"55 Powdery Street, Boston",80743,844-076-5141,9,2012-08-10 14:23:22
13,13,Farrell,Jemima,"103 Firth Avenue, North Reading",57392,(855) 016-0163,0,2012-08-10 14:28:01
14,14,Smith,Jack,"252 Binkington Way, Boston",69302,(822) 163-3254,1,2012-08-10 16:22:05
15,15,Bader,Florence,"264 Ursula Drive, Westford",84923,(833) 499-3527,9,2012-08-10 17:52:03
16,16,Baker,Timothy,"329 James Street, Reading",58393,833-941-0824,13,2012-08-15 10:34:25
17,17,Pinker,David,"5 Impreza Road, Boston",65332,811 409-6734,13,2012-08-16 11:32:47
18,20,Genting,Matthew,"4 Nunnington Place, Wingfield, Boston",52365,(811) 972-1377,5,2012-08-19 14:55:55
19,21,Mackenzie,Anna,"64 Perkington Lane, Reading",64577,(822) 661-2898,1,2012-08-26 09:32:05
20,22,Coplin,Joan,"85 Bard Street, Bloomington, Boston",43533,(822) 499-2232,16,2012-08-29 08:32:41
21,24,Sarwin,Ramnaresh,"12 Bullington Lane, Boston",65464,(822) 413-1470,15,2012-09-01 08:44:42
22,26,Jones,Douglas,"976 Gnats Close, Reading",11986,844 536-8036,11,2012-09-02 18:43:05
23,27,Rumney,Henrietta,"3 Burkington Plaza, Boston",78533,(822) 989-8876,20,2012-09-05 08:42:35
24,28,Farrell,David,"437 Granite Farm Road, Westford",43532,(855) 755-9876,0,2012-09-15 08:22:05
25,29,Worthington-Smyth,Henry,"55 Jagbi Way, North Reading",97676,(855) 894-3758,2,2012-09-17 12:27:15
26,30,Purview,Millicent,"641 Drudgery Close, Burnington, Boston",34232,(855) 941-9786,2,2012-09-18 19:04:01
27,33,Tupperware,Hyacinth,"33 Cheerful Plaza, Drake Road, Westford",68666,(822) 665-5327,0,2012-09-18 19:32:05
28,35,Hunt,John,"5 Bullington Lane, Boston",54333,(899) 720-6978,30,2012-09-19 11:32:45
29,36,Crumpet,Erica,"Crimson Road, North Reading",75655,(811) 732-4816,2,2012-09-22 08:36:38
30,37,Smith,Darren,"3 Funktown, Denzington, Boston",66796,(822) 577-3541,0,2012-09-26 18:08:45

# **The Facilities Table**

In [27]:
query_facilities = """SELECT *
                    FROM facilities;"""

# Execute the query using pd.read_sql
df_facilities = pd.read_sql(query_facilities, conn)

display(df_facilities)

,facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
0,0,Tennis Court 1,5.0,25.0,10000,200
1,1,Tennis Court 2,5.0,25.0,8000,200
2,2,Badminton Court,0.0,15.5,4000,50
3,3,Table Tennis,0.0,5.0,320,10
4,4,Massage Room 1,35.0,80.0,4000,3000
5,5,Massage Room 2,35.0,80.0,4000,3000
6,6,Squash Court,3.5,17.5,5000,80
7,7,Snooker Table,0.0,5.0,450,15
8,8,Pool Table,0.0,5.0,400,15



---


# **Exploring the Dataset with Directed Questions**

In [28]:
#Q1: You'd like to get the first and last name of the last member(s) who signed up. Try not to use the LIMIT clause for your solution.
query_last_member = """
                    SELECT firstname ||" "|| surname AS "Full Name", joindate
                    FROM members
                    WHERE joindate = (SELECT MAX(joindate) FROM members);
                    """
   # I can't think of a better way to do this.

pd.read_sql(query_last_member, conn)

      Full Name             joindate
0  Darren Smith  2012-09-26 18:08:45

In [29]:
#Q2: Produce a list of all members who have used a tennis court.
#Include in your output the name of the court, and the name of the member formatted as a single column. Ensure no duplicate data, and order by the member name.
query_tennis_courts = """
                      SELECT DISTINCT m.firstname ||" "|| m.surname AS "Full Name", f.name AS "Court Name"
                      FROM members m
                      JOIN bookings b ON m.memid = b.memid
                      JOIN facilities f ON b.facid = b.facid
                      WHERE f.facid = 0 OR f.facid = 1
                      ORDER BY m.surname ASC;
                      """

# pd.read_sql(query_tennis_courts, conn)

In [30]:
#Q3: Produce a report of members and who recommended them in alphabetic surname,firstname order
query_recommended_by = """
                       SELECT DISTINCT m1.firstname ||" "|| m1.surname AS "Full Name", m2.firstname||" "||m2.surname AS "Recommended Name"
                       FROM members m1, members m2
                       JOIN members m3 ON m1.recommendedby = m2.memid
                       WHERE m1.recommendedby != 0
                       ORDER BY m1.surname;
                       """

# pd.read_sql(query_recommended_by, conn)

In [31]:
#Q4: Some of the facilities charge a fee to members, but some do not. Please list the names of the facilities that do.
query_member_fee = """
                   SELECT name AS Facility
                   FROM facilities
                   WHERE membercost > 0
                   """
pd.read_sql(query_member_fee, conn)

         Facility
0  Tennis Court 1
1  Tennis Court 2
2  Massage Room 1
3  Massage Room 2
4    Squash Court

In [32]:
# REPEAT QUESTION: SKIP

#Q5: Some of the facilities charge a fee to members, but some do not.
#Write a SQL query to produce a list of the names of the facilities that do.

# query_member_fee = """

In [33]:
#Q6: How many facilities do not charge a fee to members?
query_no_member_fee = """
                      SELECT COUNT(name)
                      FROM facilities
                      WHERE membercost = 0
                      """

pd.read_sql(query_no_member_fee, conn)

   COUNT(name)
0            4

In [34]:
#Q7: Write an SQL query to show a list of facilities that charge a fee to members,
#where the fee is less than 20% of the facility's monthly maintenance cost.
#Return the facid, facility name, member cost, and monthly maintenance of the
#facilities in question.

query_member_fee_less = """
                        SELECT facid AS "ID", name AS "Facility", membercost AS "Cost", monthlymaintenance As "Monthly Maintenance"
                        FROM facilities
                        WHERE membercost < (monthlymaintenance * .2) AND membercost > 0
                        """

pd.read_sql(query_member_fee_less, conn)

   ID        Facility  Cost  Monthly Maintenance
0   0  Tennis Court 1   5.0                  200
1   1  Tennis Court 2   5.0                  200
2   4  Massage Room 1  35.0                 3000
3   5  Massage Room 2  35.0                 3000
4   6    Squash Court   3.5                   80

In [35]:
#Q8: Write an SQL query to retrieve the details of facilities with ID 1 and 5.
query_facid_1_5 = """
                  SELECT *
                  FROM facilities
                  WHERE facid = 1 OR facid = 5
                  """

pd.read_sql(query_facid_1_5, conn)

,facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
0,1,Tennis Court 2,5.0,25.0,8000,200
1,5,Massage Room 2,35.0,80.0,4000,3000

In [36]:
#Q9: Produce a list of facilities, with each labelled as 'cheap' or 'expensive', depending on if their monthly maintenance cost is more than $100.
#Return the name and monthly maintenance of the facilities in question.
query_cheap_expensive = """
                        SELECT name, monthlymaintenance,
                            CASE
                                WHEN monthlymaintenance > 100 THEN "expensive"
                                WHEN monthlymaintenance < 100 THEN "cheap"
                                ELSE "equal to 100"
                            END as costlabel
                        FROM facilities;
                        """

pd.read_sql(query_cheap_expensive, conn)

              name  monthlymaintenance  costlabel
0   Tennis Court 1                 200  expensive
1   Tennis Court 2                 200  expensive
2  Badminton Court                  50      cheap
3     Table Tennis                  10      cheap
4   Massage Room 1                3000  expensive
5   Massage Room 2                3000  expensive
6     Squash Court                  80      cheap
7    Snooker Table                  15      cheap
8       Pool Table                  15      cheap

In [37]:
#Q10: Produce a list of facilities with a total revenue less than 1000.
#The output of facility name and total revenue, sorted by revenue.
#Remember that there's a different cost for guests and members!
query_total_revenue = """
                      SELECT SUM(
                        CASE
                            WHEN memid > 0 THEN membercost
                            WHEN memid = 0 THEN guestcost
                            ELSE "unknown"
                        END) as "total_revenue"
                      FROM facilities f
                      JOIN bookings b ON b.facid = f.facid
                      GROUP BY name
                      HAVING total_revenue < 1000
                      """

pd.read_sql(query_total_revenue, conn)

   total_revenue
0          604.5
1          265.0
2          115.0
3           90.0

In [38]:
# This is my solution. I thought the question was asking for facility usage by member, not how each member uses each facility. 
# The next cell contains the in-class code.

#Q11: Find the facilities with their usage by member, but not guests
query_usage_by = """
                 SELECT name, CAST(SUM(
                    CASE
                        WHEN memid > 0 THEN 1
                        WHEN memid = 0 THEN 0
                        ELSE 0
                    END)AS FLOAT)/count(memid) as member_usage
                 FROM facilities f
                 JOIN bookings b ON b.facid = f.facid
                 GROUP BY name
                 """

# By facility. I'm not certain if we wanted a % or number usage, so I'm going with the former to be safe.
# For example, with the Massage Rooms, 66.9% of users in Room 1 are members, but only 24.3% users in Room 2 are members.

pd.read_sql(query_usage_by, conn)

              name  member_usage
0  Badminton Court      0.898172
1   Massage Room 1      0.669316
2   Massage Room 2      0.243243
3       Pool Table      0.936679
4    Snooker Table      0.948198
5     Squash Court      0.443182
6     Table Tennis      0.955335
7   Tennis Court 1      0.754902
8   Tennis Court 2      0.709512

In [39]:
# In-class code for Q11.

query_usage_by_in_class = """
                          SELECT f.name AS facility_name, m.firstname ||" "|| m.surname AS fullname, SUM(b.slots) AS usage
                          FROM bookings b
                          JOIN facilities f ON b.facid = f.facid
                          JOIN members m ON b.memid = m.memid
                          WHERE b.memid != 0
                          GROUP BY f.name, m.firstname, m.surname
                          ORDER BY m.surname, m.firstname;
                          """

pd.read_sql(query_usage_by_in_class, conn)

       facility_name                 fullname  usage
0    Badminton Court           Florence Bader     27
1     Massage Room 2           Florence Bader      4
2         Pool Table           Florence Bader     23
3      Snooker Table           Florence Bader     66
4       Squash Court           Florence Bader      4
..               ...                      ...    ...
197     Squash Court      Hyacinth Tupperware      2
198  Badminton Court  Henry Worthington-Smyth     15
199   Massage Room 1  Henry Worthington-Smyth      2
200       Pool Table  Henry Worthington-Smyth     37
201     Table Tennis  Henry Worthington-Smyth      6

[202 rows x 3 columns]

In [40]:
#Q12: Find the facilities usage by month. Exclude guests
query_usage_ = """
               SELECT SUBSTRING(starttime, 6, 2) as month, f.name AS facility_name, SUM(b.slots) AS usage
               FROM facilities f 
               JOIN bookings b ON b.facid = f.facid
               WHERE b.memid != 0
               GROUP BY month, facility_name
               ORDER BY month, facility_name;
               """

pd.read_sql(query_usage_, conn)

   month    facility_name  usage
0     01       Pool Table      1
1     07  Badminton Court    165
2     07   Massage Room 1    166
3     07   Massage Room 2      8
4     07       Pool Table    110
5     07    Snooker Table    140
6     07     Squash Court     50
7     07     Table Tennis     98
8     07   Tennis Court 1    201
9     07   Tennis Court 2    123
10    08  Badminton Court    414
11    08   Massage Room 1    316
12    08   Massage Room 2     18
13    08       Pool Table    303
14    08    Snooker Table    316
15    08     Squash Court    184
16    08     Table Tennis    296
17    08   Tennis Court 1    339
18    08   Tennis Court 2    345
19    09  Badminton Court    507
20    09   Massage Room 1    402
21    09   Massage Room 2     28
22    09       Pool Table    443
23    09    Snooker Table    404
24    09     Squash Court    184
25    09     Table Tennis    400
26    09   Tennis Court 1    417
27    09   Tennis Court 2    414

# **1. Revenue & Financial KPIs**

**Total Revenue per Facility:**

Summing booking slots multiplied by facility costs (guest vs. member rates) to determine which facilities generate the most income.

In [41]:
total_revenue_per_facility = """
                             SELECT f.name AS facility_name, SUM(
                             CASE
                                WHEN b.memid = 0 THEN f.guestcost * b.slots
                                ELSE f.membercost * b.slots
                             END) AS total_revenue
                             FROM bookings b
                             JOIN facilities f ON b.facid = f.facid
                             GROUP BY facility_name
                             ORDER BY total_revenue DESC;
                             """

pd.read_sql(total_revenue_per_facility, conn)

     facility_name  total_revenue
0   Massage Room 1        72540.0
1   Massage Room 2        15810.0
2   Tennis Court 2        14310.0
3   Tennis Court 1        13860.0
4     Squash Court        13468.0
5  Badminton Court         1906.5
6       Pool Table          270.0
7    Snooker Table          240.0
8     Table Tennis          180.0

**Average Revenue per Member (ARPM):**

Calculate the total spending (fees + booking costs) per member to identify high-value users.

In [110]:
average_revenue_per_member = """
                             SELECT m.firstname ||" "|| m.surname AS "Member Name", SUM(f.membercost * b.slots) AS "Total Spent"
                             FROM members m
                             JOIN bookings b ON b.memid = m.memid
                             JOIN facilities f on f.facid = b.facid
                             WHERE m.memid != 0
                             GROUP BY "Member Name"
                             ORDER BY "Total Spent" DESC
                             """

pd.read_sql(average_revenue_per_member, conn)

                Member Name  Total Spent
0                Tim Rownam       6480.0
1                Tim Boothe       3644.0
2            Gerald Butters       3343.0
3              Burton Tracy       2953.0
4               David Jones       2651.0
5            Jemima Farrell       2466.0
6                Jack Smith       2427.0
7              Darren Smith       2420.0
8                Nancy Dare       2250.0
9             Timothy Baker       2115.0
10             Charles Owen       1919.0
11          Ponder Stibbons       1909.0
12          Matthew Genting       1905.0
13          Janice Joplette       1490.0
14               Anne Baker       1395.0
15         Ramnaresh Sarwin       1039.0
16              Tracy Smith        957.0
17             David Pinker        486.0
18                John Hunt        337.0
19              Joan Coplin        322.0
20           Florence Bader        289.0
21            Erica Crumpet        155.0
22            Douglas Jones        142.0
23            David Farrell        112.0
24           Anna Mackenzie         84.0
25      Hyacinth Tupperware         77.0
26  Henry Worthington-Smyth         70.0
27         Henrietta Rumney         29.0
28        Millicent Purview         22.0

**Guest Fee Revenue:**
Total income generated specifically from non-member guests, indicating the popularity of the club with outside visitors.

In [ ]:
## My solution
guest_fee_revenue = """
                    SELECT SUM(f.guestcost * b.slots) AS "Guest Income"
                    FROM bookings b
                    JOIN facilities f on f.facid = b.facid
                    WHERE b.memid = 0
                    """

## In-class solution
query_guest_fee = """SELECT SUM(
                            CASE
                                WHEN b.memid = 0 THEN f.guestcost * b.slots
                                ELSE 0
                            END) AS guest_fee
                            FROM bookings b
                            JOIN facilities as f ON b.facid = f.facid;
                    """

print("My solution")
display(pd.read_sql(guest_fee_revenue, conn))
print("In-class solution")
display(pd.read_sql(query_guest_fee, conn))

My solution

   Guest Income
0       89096.5

In-class solution

   guest_fee
0    89096.5

**Facility Cost Recovery:**
Comparing the revenue generated by a facility to the frequency of its use to determine if rates need adjustment.

In [185]:
facility_cost_recovery = """
                         SELECT f.name AS Facility, SUM(
                         CASE
                            WHEN memid > 0 THEN membercost * slots
                            ELSE guestcost * slots
                         END) AS Revenue, SUM(slots) AS Usage
                         FROM facilities f
                         JOIN bookings b ON b.facid = f.facid
                         GROUP BY f.name
                         """

## Unable to figure out how to do revenue over usage

pd.read_sql(facility_cost_recovery, conn)

          Facility  Revenue  Usage
0  Badminton Court   1906.5   1209
1   Massage Room 1  72540.0   1404
2   Massage Room 2  15810.0    228
3       Pool Table    270.0    911
4    Snooker Table    240.0    908
5     Squash Court  13468.0   1104
6     Table Tennis    180.0    830
7   Tennis Court 1  13860.0   1320
8   Tennis Court 2  14310.0   1278

# **2. Usage & Operational KPIs**

**Facility Utilization Rate (Booking Density):** The ratio of booked hours to total available operating hours for facilities

In [ ]:
query_advocates = """SELECT COUNT()"""

**Member-to-Guest Ratio:** Tracking how many guests are brought by members to measure member satisfaction (acting as advocates).



---


# **Furthering Our Business Understanding**